name: melodymarket
description: "Unleash your inner music mogul with this vibrant app, empowering artists to directly sell their tracks and albums while creating a personalized, offline-ready listening experience for fans."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.0.0
  audioplayers: ^6.0.0
  image_picker: '>=1.1.2'
  path_provider: ^2.0.0
  file_picker: '>=8.1.2'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
